language: node_js
node_js:
    - "stable"
cache:
  directories:
    - node_modules
before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
install:
    - conda create --yes -n test-env python=3.5
    - source activate test-env
    - pip install git+https://github.com/qiime2/qiime2.git
    - pip install flake8
    - pip install .
    - pip install -q https://github.com/qiime2/q2lint/archive/master.zip
    - make clean
before_script:
    - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
script:
    - make test-cov
    - make lint
