# ----------------------------------------------------------------------------
# Copyright (c) 2016-2019, QIIME 2 development team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------

extends: stylelint-config-standard
rules:
    # PEP8 uses 4 spaces, it's just easier this way.
    indentation: 4
