name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v2

    - name: set up python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: install dependencies
      run: python -m pip install --upgrade pip

    - name: lint
      run: |
        pip install -q https://github.com/qiime2/q2lint/archive/master.zip
        q2lint --disable-install-requires-check
        pip install -q flake8
        flake8

  verify:
    runs-on: ubuntu-latest
    env:
      DISPLAY: :0
    steps:
    - name: checkout source
      uses: actions/checkout@v2

    - name: install QIIME 2 core distro
      run: |
        envFile=qiime2-latest-py36-linux-conda.yml
        wget https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/$envFile
        conda env create -q -p ./test-env --file $envFile

    - name: install system dependencies
      run: |
        sudo apt install -y libgconf-2-4 xvfb libgtk2.0-0

    - name: build
      shell: bash -l {0}
      run: |
        source "$CONDA/etc/profile.d/conda.sh"
        conda activate ./test-env
        make test
